# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GDriveIOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GDriveIOS
  pod 'GoogleSignIn'

  target 'GDriveIOS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GDriveIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GDriveIOS-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GDriveIOS-tvOS


end
